name: Release

on:
  workflow_dispatch:

env:
  IMAGE_NAME: "landing"

jobs:
  release-prod:
    environment:
      name: production
      url: https://festic.ru

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          file: docker/production/Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
